### ISSUE TITLE
springboot没有数据库文件，老哥方便发下sql文件吗

### ISSUE THREAD

**Issue by YangTao-China** [wxyShine/springboot_vue_shop#1]
如题，老哥我也在看你的springboot项目，但是么的数据库文件emmmmm ，老哥方便发下嘛

**Comment by wxyShine** [comment]
我用的jpa你修改数据库配置运行项目会自动创建表～留个邮箱吧我发你sql

**Comment by YangTao-China** [comment]
好的老哥谢谢了，我的邮箱 208820388@qq.com   qq也是208820388,老哥方便加下好友嘛，一起学习，我叫杨涛，我是18级的，也在学习springboot+vue 这一块emmmmmm

**Comment by wrf19970817** [comment]
610130817@qq.com麻烦博主给我也发一份，谢谢
